# xpCost - How much player will spend converting his xp to bottles
# xpEarn - How much player will get xp from xp bottle
# useItems - Do you want to use custom items when converting xp to xp bottles
# consumedItem - Id for custom item, by default its empty glass bottle
# amountConsumed - How many to consume when converting. This is for every bottle you will get
# useMoney - Do you want to charge money for xp conversion
# moneyCost - How much it will gonna cost
# useBottleMoney - Do you want to show extra information for how much its gonna cost to level up
# bottleCost - How much one xp bottle costs
# ShowEnchant - Do you want to show all enchantments player gets after enchanting item
# UseThreeButtonEnchant - Do you want to use new 1.8 enchant system
# UseGiveCommand - Do you want to enable give command
# LostDurringTransfer - How much exp will be lost during trasfer in percentage
# UseRightClick - Do you want to use right click, if false then left will be used, good for block with interactions like enchant table
# BlockId - Id of block will be used to convert xp to bottles
# HandItemId - Id of item in hand when you want to convert xp by clicking block
# GiveEveryTime - How many bottles to give everytime
# Multiplayer - How many times to multiply given bottles by clicking shift

bottle:
  xpCost: 10
  xpEarn: 10
  useItems: false
  consumedItem: 374
  amountConsumed: 1
  useMoney: false
  moneyCost: 100.0
  useBottleMoney: false
  bottleCost: 3.25
  ShowEnchant: false
  UseThreeButtonEnchant: true
  give:
    UseGiveCommand: false
    LostDurringTransfer: 0
  BlockInteraction:
    Use: false
    UseRightClick: false
    BlockId: 116
    HandItemId: 374
    GiveEveryTime: 1
    Multiplayer: 10
language:
  errAmount: '&4The amount has to be a number!'
  errXP: '&4You don''t have enough XP!'
  errMoney: '&4You don''t have enough money!'
  currentXP: '&2You currently have &3{xp} &2xp and you are at lvl &3{level}&2!'
  currentXP2: '&2You still need &3{xpdelta} &2xp or &3{bottles} &2bottles for next
    level!'
  order: '&2You have ordered: &3{bottles} &2bottles!'
  refund: '&2Refund issued! Amount: &3{amount}'
  itemConsume: '&4You don''t have enough items!'
  money: '&eTransaction cost: &3{cost}'
  enchant: '&2You have spend &3{xp} &2xp for this enchantment'
  morexp: '&4Players earn more XP through XP bottles than they cost!'
  noperm: '&4You don''t have permission to do this!'
  give:
    notOnline: '&4Player is not online!'
    yourSelf: '&4You cant send exp for yourself'
    notEnough: '&4You dont have enough exp to give'
    plzuse: '&4Plz use /bottle give [nick] [amount]'
    positive: '&4Plz give positive number'
    sender: '&2You just send &3{amount} &2xp to &3{name} &2and &3{lost} &2xp was lost
      during transfer'
    receiver: '&2You just got &3{amount} &2xp from &3{name} &2and &3{lost} &2xp was
      lost during transfer'
    giveDisabled: '&4Give command is disabled!'
