bottle:
#How much player will spend converting his xp to bottles
  xpCost: 10
#How much player will get xp from xp bottle
  xpEarn: 10
#Do you want to use custom items when converting xp to xp bottles
  useItems: false
#Id for custom item, by default its empty glass bottle
  consumedItem: 374
#How many to consume when converting. This is for every bottle you will get
  amountConsumed: 1
#Do you want to charge money for xp conversion
  useMoney: false
#How much it will gonna cost
  moneyCost: 100.0
#Do you want to show extra information for how much its gonna cost to level up
  useBottleMoney: false
#How much one xp bottle costs
  bottleCost: 3.25
#Do you want to show all enchantments player gets after enchanting item
  ShowEnchant: false
#Do you want to use new 1.8 enchant system
  UseThreeButtonEnchant: true
  give:
#Do you want to enable give command
    UseGiveCommand: true
#How much exp will be lost during trasfer in percentage
    LostDurringTransfer: 5
language:
  errAmount: '&4The amount has to be a number!'
  errXP: '&4You don''t have enough XP!'
  errMoney: '&4You don''t have enough money!'
  currentXP: '&2You currently have &3{xp} &2xp and you are at lvl &3{level}&2!'
  currentXP2: '&2You still need &3{xpdelta} &2xp or &3{bottles} &2bottles for next
    level!'
  order: '&2You have ordered: &3{bottles} &2bottles!'
  refund: '&2Refund issued! Amount: &3{amount}'
  itemConsume: '&4You don''t have enough items!'
  money: '&eTransaction cost: &3{cost}'
  enchant: '&2You have spend &3{xp} &2xp for this enchantment'
  morexp: '&4Players earn more XP through XP bottles than they cost!'
  noperm: '&4You don''t have permission to do this!'
  give:
    notOnline: '&4Player is not online!'
    yourSelf: '&4You cant send exp for yourself'
    notEnough: '&4You dont have enough exp to give'
    plzuse: '&4Plz use /bottle give [nick] [amount]'
    positive: '&4Plz give positive number'
    sender: '&2You just send &3{amount} &2xp to &3{name} &2and &3{lost} &2xp was lost
      during transfer'
    receiver: '&2You just got &3{amount} &2xp from &3{name} &2and &3{lost} &2xp was
      lost during transfer'
    giveDisabled: '&4Give command is disabled!'
