name: BottledExp
version: 1.8.0
description: Fills the player's XP into a bottle
author: sacnoth
website: http://www.spigotmc.org/resources/bottledexp.2815/

main: me.sacnoth.bottledexp.BottledExp
database: false
softdepend: [PermissionsEx, Vault]

commands:
   bottle:
      description: Fills XP into a bottle.
      usage: /<command> [amount]
      permission-message: You don't have permission to do this